version: '3.8'
services:
  database:
    image: mysql
    env_file:
      - .env
    ports:
      - '3306:3306'
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - var/lib/mysql
    networks:
      - network
networks:
  network:
    driver: bridge